2 lesson 02 hw
v-shchenyatskiy/3-javascript-2-pro pull request #2
Opened 2021-01-27 13:33 UTC by v-shchenyatskiy

Сделал расчет бургера для стандартного (big, little) и кастомного

2021-01-28 15:49 UTC, Om1X requested changes

2021-01-28 15:49 UTC, Om1X commented on 2_Les_02_hw/js/burger.js
> +        if (!order) { order = "custom"; }
пишем просто `constructor(order = 'custom')`

2021-01-28 15:49 UTC, Om1X commented on 2_Les_02_hw/js/burger.js
> +        this._id = 0;
такие данные, которые могут изменяться по ходу работы приложения, лучше оформлять как методы, которые будут считать эти значения и возвращать их.

2021-01-28 15:49 UTC, Om1X commented on 2_Les_02_hw/js/burger.js
> +        const id = this._id;
с id как-то не совсем очевидно и понятно.

2021-01-28 15:49 UTC, Om1X commented on 2_Les_02_hw/js/burger.js
> +        this.calories = 0;
здесь аналогично, нужно заменить методами.

2021-01-28 15:49 UTC, Om1X commented on 2_Les_02_hw/js/main.js
> +    addToCart(product, quantity=undefined, img=undefined) {
Зачем undefined? Они итак будут undefined если ничего не передавать.

2021-01-28 15:49 UTC, Om1X commented on 2_Les_02_hw/js/main.js
> +        this.amount = 0;
и тут такое же замечание, меняем на методы.

2021-01-28 15:49 UTC, Om1X commented on 2_Les_02_hw/js/main.js
> +        this.countGoods = this._countGoods();
зачем дублировать данные? Ведь мы всегда можем "дернуть" метод и получить данные, всего одним действием. А так получается вы вызываете метод и его результат куда-то записываете а уже потом обращаетесь туда.

2021-01-28 15:49 UTC, Om1X commented on 2_Les_02_hw/js/main.js
> +        this._updateSums();
Какой-то уж совсем грубый код. Метод подразумевает удаление, ожидает 2 параметра и один вообще не используется и довесок еще и "перетирает" список товаров.

2021-01-28 15:49 UTC, Om1X commented on 2_Les_02_hw/js/main.js
> +    }
можно упростить реализовав через `return this.items.reduce(...)`

2021-01-29 13:06 UTC, v-shchenyatskiy commented on 2_Les_02_hw/js/main.js
> +    addToCart(product, quantity=undefined, img=undefined) {
Если поставить undefined, как значение по умолчанию, то в этом случае консоль браузера при наборе функции будет подсказывать, что этот параметр не является обязательным.
Например,
1)  let test = a => console.log(a) при вызове test() подскажет f( a )
2)  let test = ( a = undefined ) => console.log(a) при вызове test() подскажет f( ?a )
В обоих случаях a = undefined, только в первом случае ожидаешь ошибку, если а не передаешь, а во втором понятно, что параметр не обязательный

2021-01-29 14:38 UTC, merged